name: Build

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*

  pull_request:
    branches:
    - master
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 13, 15, 16 ]
    env:
      JDK_VER: ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK ${{ env.JDK_VER }}
      uses: actions/setup-java@v2.3.1
      with:
        distribution: 'adopt'
        java-version: ${{ env.JDK_VER }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    env:
      JDK_VER: 11
    steps:
      - uses: actions/checkout@v2
      - name: Set up OpenJDK ${{ env.JDK_VER }}
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VER }}
